課題１完了
shell0325/todolist pull request #1
Opened 2020-11-11 12:23 UTC by shell0325

2020-11-17 12:21 UTC, myzktkyk requested changes
動作としては問題ないです。
…なのですが、この後の課題にあるタスク状態変更機能を追加する際に今の実装だとかなり苦労をします。
（タスクの状態を管理しなくてはならない為）

ちょっと大変ですが、今のうちに以下のような実装方法に変更をお願いしたいです 🙏 

1. 入力されたタスク内容とその状態（デフォルトでは作業中）をオブジェクトで管理する
2. 上記のオブジェクトをはtodosという名前の配列に追加することで、複数のタスクを管理する。
3. todo配列の内容を表示させる関数（displayTodos）を定義する

オブジェクトの内容は以下のような感じになります。

```
todo = {
            task: '入力されたタスク'
            status: '作業中'
       }

```

タスクが入力される度に、このtodoをtodosという配列にpushし、todos配列にタスクをためていく感じです。

2020-12-04 01:25 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-12-04 01:25 UTC, kouki-iwahara commented on js/todo.js
> +const add_btn = document.getElementById("add_btn");
jsではキャメルケースで定義しましょう。
他の箇所も同様です。

2020-12-04 01:25 UTC, kouki-iwahara commented on js/todo.js
> +  add_value.textContent = "";
jsでは文字列を`''`で囲むのが慣習ですので修正しましょう。

2020-12-04 01:25 UTC, kouki-iwahara commented on js/todo.js
> +    // console.log(`${index}: ${todo.Taskid}`);
不要なコメントアウトですので、削除しましょう。

2020-12-04 01:25 UTC, kouki-iwahara commented on js/todo.js
> +add_btn.addEventListener("click", function () {
このボタンの処理はtodo追加の処理ですので、addTodoなどの名前をつけて関数化しましょう。

2020-12-04 01:25 UTC, kouki-iwahara commented on js/todo.js
> +    status: status,
オブジェクトはkeyとvalueが同じなら、以下のように省略できます。
`{ status }`

2020-12-04 01:25 UTC, kouki-iwahara commented on js/todo.js
> +    workButton.addEventListener("click", function () {
次に使用される予定でしょうか？
なるべく要件から外れる記述は避けましょう。

2020-12-04 01:25 UTC, kouki-iwahara commented on js/todo.js
> +    removeButton.addEventListener("click", function () {
コールバックもアロー関数で定義すると良いです。

2020-12-04 01:25 UTC, kouki-iwahara commented on js/todo.js
> +const displayTodos = (todos) => {
todo表示の関数の中にボタンを作成する処理が混じっていますので、状態ボタンを生成する関数と削除ボタンを生成する関数を作成し、処理を切る分けると良いです。

2020-12-04 01:25 UTC, kouki-iwahara commented on js/todo.js
> +    const reset = document.getElementById("add_text");
同じ要素を違う名前で定義していたりと可読性が少し低いかなと思います。
この要素は一度グローバルで定義してしまっても良いかなと思いますが、スコープが気になるようでしたら同じ名前で定義すると良いです。

2020-12-09 01:28 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-12-09 01:28 UTC, kouki-iwahara commented on js/todo.js
> +  const Taskid = todos.length;
ここだけ先頭が大文字で定義されていますが、特別な理由がないのであれば他と同様に小文字で、キャメルケースで定義しましょう。

2020-12-09 01:28 UTC, kouki-iwahara commented on js/todo.js
> +const createstatusbutton = function () {
アロー関数の定義で統一しましょう。

2020-12-09 03:55 UTC, merged